/*
This software is licensed under the BSD 2-Clause License
(http://opensource.org/licenses/BSD-2-Clause).

Copyright © 2020 - 2026 by Benilda Key

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/

#pragma once

#ifndef VersionInfoCommon_h_7171cd16
#define VersionInfoCommon_h_7171cd16

// =====================================================================
// The following preprocessor symbol definitions should be updated for
// each release.
// =====================================================================

#ifndef VER_FILE_VERSION_MAJOR
#  define VER_FILE_VERSION_MAJOR 26
#endif
#ifndef VER_FILE_VERSION_MINOR
#  define VER_FILE_VERSION_MINOR 7
#endif
#ifndef VER_FILE_VERSION_BUILD
#  define VER_FILE_VERSION_BUILD 1
#endif
#ifndef VER_FILE_VERSION_REVISION
#  define VER_FILE_VERSION_REVISION 0
#endif
#ifndef VER_PRODUCT_VERSION_MAJOR
#  define VER_PRODUCT_VERSION_MAJOR 2026
#endif
#ifndef VER_PRODUCT_VERSION_MINOR
#  define VER_PRODUCT_VERSION_MINOR 2607
#endif
#ifndef VER_PRODUCT_VERSION_BUILD
#  define VER_PRODUCT_VERSION_BUILD 1
#endif
#ifndef VER_PRODUCT_VERSION_REVISION
#  define VER_PRODUCT_VERSION_REVISION 0
#endif

#define VER_BUILD_YEAR 2026
#define VER_BUILD_YEAR_STRING "2026"

// =====================================================================
// It should not be necessary to make any changes below this line.
// =====================================================================

#define STRINGIZER(x) #x
#define VERSION_STRING(major, minor, build, revision) STRINGIZER(major) "." STRINGIZER(minor) "." STRINGIZER(build) "." STRINGIZER(revision)
#define VERSION_STRING_SHORT(major, minor, build) STRINGIZER(major) "." STRINGIZER(minor) "." STRINGIZER(build)
#define VERSION_STRING_MAJOR_AND_MINOR(major, minor) STRINGIZER(major) "." STRINGIZER(minor)

#undef VER_FILE_VERSION
#define VER_FILE_VERSION VER_FILE_VERSION_MAJOR, VER_FILE_VERSION_MINOR, VER_FILE_VERSION_BUILD, VER_FILE_VERSION_REVISION

#undef VER_PRODUCT_VERSION
#define VER_PRODUCT_VERSION VER_PRODUCT_VERSION_MAJOR, VER_PRODUCT_VERSION_MINOR, VER_PRODUCT_VERSION_BUILD, VER_PRODUCT_VERSION_REVISION

#if defined(_WIN32)

#  ifndef VER_FILE_FLAGS_MASK
#    define VER_FILE_FLAGS_MASK VS_FFI_FILEFLAGSMASK
#  endif

#  ifndef VER_FILE_FLAGS
#    ifdef _DEBUG
#      define DBG 1
#    else
#      define OFFICIAL_BUILD 1
#    endif // _DEBUG
#    ifndef VER_DEBUG
#      if DBG
#        define VER_DEBUG VS_FF_DEBUG
#      else
#        define VER_DEBUG 0
#      endif
#    endif // VER_DEBUG
#    ifndef VER_PRE_RELEASE
#      if BETA
#        define VER_PRE_RELEASE VS_FF_PRERELEASE
#      else
#        define VER_PRE_RELEASE 0
#      endif
#    endif // VER_PRE_RELEASE
#    ifndef VER_PRIVATE
#      if OFFICIAL_BUILD
#        define VER_PRIVATE 0
#      else
#        define VER_PRIVATE VS_FF_PRIVATEBUILD
#      endif
#    endif // VER_PRIVATE
#    define VER_FILE_FLAGS (VER_DEBUG|VER_PRE_RELEASE|VER_PRIVATE)
#  endif // VER_FILE_FLAGS

#  ifndef VER_FILE_OS
#    define VER_FILE_OS VOS_NT_WINDOWS32
#  endif // VER_FILE_OS

#  ifndef VER_FILE_TYPE
#    define VER_FILE_TYPE VFT_APP
#  endif // VER_FILE_TYPE

#  ifndef VER_FILE_SUBTYPE
#    define VER_FILE_SUBTYPE VFT2_UNKNOWN
#  endif // VER_FILE_SUBTYPE

#  ifndef VER_VERSION_UNICODE_LANG
#    define VER_VERSION_UNICODE_LANG "040904B0" /* LANG_ENGLISH/SUBLANG_ENGLISH_US, Unicode CP */
#  endif // VER_VERSION_UNICODE_LANG

#  ifndef VER_VERSION_ANSI_LANG
#    define VER_VERSION_ANSI_LANG "0c0904E4" /* LANG_ENGLISH/SUBLANG_ENGLISH_US, Ansi CP */
#  endif // VER_VERSION_ANSI_LANG

#endif // _WIN32

#undef VER_COMPANY_NAME_STR
#define VER_COMPANY_NAME_STR "Benilda Key"

#ifndef VER_FILE_VERSION_STR
#  define VER_FILE_VERSION_STR VERSION_STRING(VER_FILE_VERSION_MAJOR, VER_FILE_VERSION_MINOR, VER_FILE_VERSION_BUILD, VER_FILE_VERSION_REVISION)
#endif // VER_FILE_VERSION_STR
#ifndef VER_FILE_VERSION_STR_SHORT
#  define VER_FILE_VERSION_STR_SHORT VERSION_STRING_SHORT(VER_FILE_VERSION_MAJOR, VER_FILE_VERSION_MINOR, VER_FILE_VERSION_BUILD)
#endif // VER_FILE_VERSION_STR_SHORT
#ifndef VER_FILE_VERSION_STR_MAJOR_AND_MINOR
#  define VER_FILE_VERSION_STR_MAJOR_AND_MINOR VERSION_STRING_MAJOR_AND_MINOR(VER_FILE_VERSION_MAJOR, VER_FILE_VERSION_MINOR)
#endif // VER_FILE_VERSION_STR_SHORT

#if defined(VER_START_YEAR) && defined(VER_START_YEAR_STRING) && (VER_START_YEAR != VER_BUILD_YEAR)
#  define VER_LEGAL_COPYRIGHT_YEARS VER_START_YEAR_STRING " - " VER_BUILD_YEAR_STRING
#else
#  define VER_LEGAL_COPYRIGHT_YEARS VER_BUILD_YEAR_STRING
#endif // VER_START_YEAR_STRING
#define VER_LEGAL_COPYRIGHT_STR "Copyright © " VER_LEGAL_COPYRIGHT_YEARS ", " VER_COMPANY_NAME_STR ". All rights reserved."

#ifndef VER_PRODUCT_VERSION_STR
#  define VER_PRODUCT_VERSION_STR VERSION_STRING(VER_PRODUCT_VERSION_MAJOR, VER_PRODUCT_VERSION_MINOR, VER_PRODUCT_VERSION_BUILD, VER_PRODUCT_VERSION_REVISION)
#endif // VER_PRODUCT_VERSION_STR
#ifndef VER_PRODUCT_VERSION_STR_SHORT
#  define VER_PRODUCT_VERSION_STR_SHORT VERSION_STRING_SHORT(VER_PRODUCT_VERSION_MAJOR, VER_PRODUCT_VERSION_MINOR, VER_PRODUCT_VERSION_BUILD)
#endif // VER_PRODUCT_VERSION_STR_SHORT
#ifndef VER_PRODUCT_VERSION_STR_MAJOR_AND_MINOR
#  define VER_PRODUCT_VERSION_STR_MAJOR_AND_MINOR VERSION_STRING_MAJOR_AND_MINOR(VER_PRODUCT_VERSION_MAJOR, VER_PRODUCT_VERSION_MINOR)
#endif // VER_PRODUCT_VERSION_STR_MAJOR_AND_MINOR

#ifndef VER_VERSION_TRANSLATION
#  define VER_VERSION_TRANSLATION 0x0409, 0xFDE9
#endif // VER_VERSION_TRANSLATION

#define WIDEN2(x) L##x
#define WIDEN(x) WIDEN2(x)

#ifdef VER_APP_NAME_STR
#  define VER_APP_NAME_STR_W WIDEN(VER_APP_NAME_STR)
#endif // VER_APP_NAME_STR

#define VER_COMPANY_NAME_STR_W WIDEN(VER_COMPANY_NAME_STR)

#ifdef VER_FILE_DESCRIPTION_STR
#  define VER_FILE_DESCRIPTION_STR_W WIDEN(VER_FILE_DESCRIPTION_STR)
#endif // VER_FILE_DESCRIPTION_STR

#define VER_FILE_VERSION_STR_W WIDEN(VER_FILE_VERSION_STR)
#define VER_FILE_VERSION_STR_SHORT_W WIDEN(VER_FILE_VERSION_STR_SHORT)

#ifdef VER_INTERNAL_NAME_STR
#  define VER_INTERNAL_NAME_STR_W WIDEN(VER_INTERNAL_NAME_STR)
#endif // VER_INTERNAL_NAME_STR

#define VER_LEGAL_COPYRIGHT_STR_W WIDEN(VER_LEGAL_COPYRIGHT_STR)

#ifdef VER_ORIGINAL_FILE_NAME_STR
#  define VER_ORIGINAL_FILE_NAME_STR_W WIDEN(VER_ORIGINAL_FILE_NAME_STR)
#endif // VER_ORIGINAL_FILE_NAME_STR

#ifdef VER_PRODUCT_NAME_STR
#  define VER_PRODUCT_NAME_STR_W WIDEN(VER_PRODUCT_NAME_STR)
#endif // VER_PRODUCT_NAME_STR

#define VER_PRODUCT_VERSION_STR_W WIDEN(VER_PRODUCT_VERSION_STR)
#define VER_PRODUCT_VERSION_STR_SHORT_W WIDEN(VER_PRODUCT_VERSION_STR_SHORT)
#define VER_PRODUCT_VERSION_STR_MAJOR_AND_MINOR_W WIDEN(VER_PRODUCT_VERSION_STR_MAJOR_AND_MINOR)

#endif // VersionInfoCommon_h_7171cd16
